version: "3.9"
services:
  llm-agent:
    build:
      context: ./llm_agent
      dockerfile: Dockerfile
      target: prod
    image: fastapi_rest:local_prod
    ports:
      - "8080:8080"
    env_file:
      - ./configuration/docker/local_production.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/api/v1/health/dummy-health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3


