version: "3.9"
# TODO: this is not yet developed fully !!!

services:
  llm-agent:
    build:
      context: ./llm_agent
      dockerfile: Dockerfile
      target: dev
    image: fastapi_rest:local_dev
    ports:
      - "8080:8080"
    env_file:
      - ./configuration/docker/local_development.env
    volumes:
      - ./llm_agent/llm_agent:/app/llm_agent
    command:
#       ["uvicorn","llm_agent.app:create_app","--host","0.0.0.0","--port","8080","--reload","--log-config","./llm_agent/configuration/log_config_json.json","--factory"]
       ["python", "manage.py"]
#      [ "tail", "-f", "/dev/null" ]